### ISSUE TITLE
urbandef says "All definitions not safe for work" for non existant definitions

### ISSUE THREAD

**Issue by dotslash** [dotslash/yesteapea.com#1]
Example 
==
/urbandef jigarthanda . http://www.urbandictionary.com/define.php?term=jigarthanda does not exist

**Comment by Sapeksha** [comment]
Feature request to combine to /urbandef and /define. Don't want to search the same word twice.

**Comment by Sapeksha** [comment]
Also, for NSFW definitions, provide link for user to go to directly, instead of him looking it up himself again.

**Comment by dotslash** [comment]
fixed 
(proving link for nsfw is out of scope for this ticket :p
